### ISSUE TITLE
Not working on device

### ISSUE THREAD

**Issue by glasgowm148** [k4l1sh/alexa-gpt#14]
Imported and working fine in the Test pane. But doesn't respond to those Invocation via voice on device. 

- 'Sorry I don't know that' (invocation set to 'upgrade chat')
- 'Not available in your region' ('chat chat')

Can see the skill under Dev in your skills on mobile, tried disabling/re-enabling, re-doing the process from start. All saved and built/deployed. No way to enter GPT mode from audio on device.

**Comment by k4l1sh** [comment]
It may be that "chat" is in conflict with a known invocation word in your language.
You can try changing "chat" to another word in the JSON Editor:
```json
"invocationName": "some other invocation name here",
```
After that, you can try again to say "Alexa (chosen word)" or "Echo (chosen word)" or "Amazon (chosen word)" depending on your device configurations.
If it is on the same Amazon account, enabling developer mode on the skill should also allow it to work on the device.
If that doesn't work, you can try changing the skill language/locale.

**Comment by malqudami** [comment]
Imported but not working with me. I am getting the below exception:

[ERROR]	2024-03-11T20:20:44.575Z	a7228c1b-efbb-4084-80bc-7456c81db0c8	'chat_hisory'
Traceback (most recent call last):
  File "/var/task/ask_sdk_runtime/dispatch.py", line 118, in dispatch
    output = self.__dispatch_request(handler_input)  # type: Union[Output, None]
  File "/var/task/ask_sdk_runtime/dispatch.py", line 182, in __dispatch_request
    output = supported_handler_adapter.execute(
  File "/var/task/ask_sdk_runtime/dispatch_components/request_components.py", line 437, in execute
    return handler.handle(handler_input)
  File "/var/task/lambda_function.py", line 74, in handle
    chat_history = session_attr["chat_hisory"]
KeyError: 'chat_hisory'

**Comment by k4l1sh** [comment]
You accidentally deleted a "t" in session_attr["chat_hisory"] @malqudami
it is supposed to be "chat_history"
Taking advantage of this opportunity I just pushed commit 676d40b to prevent key errors when session attributes of "chat_history" are not loaded correctly in the LaunchRequest.
